util/size.h: Fix build error for GCC < 10
Building with GCC 8.4.1 results in following build error for 'util/size.c':

../util/size.h:57:16: error: missing binary operator before token "("
   __has_builtin(__builtin_mul_overflow) && \

This is caused due to missing '__has_builtin' preprocessor operator in GCC
versions < 10.0.0. The patch updates the check for CLANG's availability of
__builtin_{mul,add}_overflow to prevent preprocessor from evaluating the
expression "___has_builtin(__builtin_mul_overflow) &&
__has_builtin(__builtin_add_overflow)".

Link: https://lore.kernel.org/r/20220226113955.526036-1-vaibhav@linux.ibm.com
Fixes:10653a171bc0("util/size.h: fix build for older compilers")
Reported-by: Tarun Sahu <tsahu@linux.ibm.com>
Reviewed-by: Joao Martins <joao.m.martins@oracle.com>
Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>
Signed-off-by: Vishal Verma <vishal.l.verma@intel.com>