ndctl, create-namespace: fix size alignment validation
Linda reports:

    I was creating a namespace on a 4-way interleave set and got an error
    I didn't expect:

    $ sudo ndctl create-namespace -m sector -s 10G -n number2
      Error: '--size=' must align to interleave-width: 4 and alignment: 2097152
      did you intend --size=12G?

    What's happening is that since I specified my size in units of G,
    the function wants the namespace to be 1G * 4 aligned rather than
    2M * 4 aligned.

Fix this by using the base "align * interleave_ways" for the alignment
check, and later calculate a 'friendly' recommended size value that
takes into account the units specified for --size.

Reported-by: Linda Knippers <linda.knippers@hpe.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>