ndctl, namespace: fix sector size default when switching modes
Maurice reports:

    I do have a question about specific behavior I observed. Before I was
    able to configure an NVDIMM into any mode from any mode. With these
    patchs if I go to sector mode and try going to memory or dax mode it
    fails with:

    # ndctl create-namespace -f -e namespace0.0 -m memory
      Error: namespace0.0: sector_size: 4096 not supported
    failed to reconfigure namespace: Invalid argument

This results from the fact that we pick up the default sector size from
the current btt. However, if the next mode is not btt we should fall
back to the native sector size of the namespace.

Validate this conversion with an extension to the 'sector-mode.sh' test.

Fixes: 61e82a3d7bc8 ("ndctl, create-namespace: support sector size...")
Reported-by: Maurice A. Saldivar <maurice.a.saldivar@hpe.com>
Tested-by: Maurice A. Saldivar <maurice.a.saldivar@hpe.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>