ndctl: autodetect ars support in ndctl.h
Kernel support for the address range scrub (ARS) set of commands was
added in the v4.3 kernel development cycle, while the base libndctl
functionality is based on the kernel provided api as of v4.2.  Support
in the library for any functionality past the base v4.2 expectations
needs to be dynamically detected and enabled.

Add autoconf machinery to do the detection as well as an override to
force use of the local ndctl.h definitions (--enable-local).  Move the
ARS routines to their own source file so they can be compiled in/out as
a complete unit.

This fixes compilation errors like the following:
    lib/libndctl.c: In function 'ndctl_bus_cmd_new_ars_start':
    lib/libndctl.c:1768:35: error: 'ARS_STATUS_MASK' undeclared (first use in this function)
      if ((*ars_cap->firmware_status & ARS_STATUS_MASK) != 0) {

Cc: Vishal Verma <vishal.l.verma@intel.com>
Reported-by: Robert Elliott <elliott@hpe.com>
Acked-by: Vishal Verma <vishal.l.verma@intel.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>