ndctl, build: Define HAVE_UUID
Attempts to build ndctl in an epel-6 environment fail with the following
messages:

    In file included from util/filter.c:24:
    ./daxctl/libdaxctl.h:22: error: redefinition of typedef 'uuid_t'
    ./ndctl/libndctl.h:26: note: previous declaration of 'uuid_t' was here

Newer compilers discard the error since it sees the types are
compatible, but the definition should be coming from uuid.h when built
with libuuid. Arrange for an AC_DEFINE for the HAVE_UUID symbol when
libuuid is detected by PKG_CHECK_MODULES.

Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Vishal Verma <vishal.l.verma@intel.com>